---

name: Unit Tests
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install python dependencies
        run: |
          pip install pipenv
          pipenv install --dev --ignore-pipfile
      # Run Tests
      - name: Unit tests
        run: pipenv run py.test --cov=drainer
